repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    api(include("io.github.spair:imgui-java-binding:$imgui_version"))
    api(include("io.github.spair:imgui-java-lwjgl3:$imgui_version")) {
        exclude group: 'org.lwjgl'
        exclude group: 'org.lwjgl.lwjgl'
    }

    runtimeOnly(include("io.github.spair:imgui-java-natives-linux:$imgui_version"))
    runtimeOnly(include("io.github.spair:imgui-java-natives-macos:$imgui_version"))
    runtimeOnly(include("io.github.spair:imgui-java-natives-windows:$imgui_version"))
}